### ISSUE TITLE
Get/Post using Requests should have timeout

### ISSUE THREAD

**Issue by menghoumenghou** [imlonghao/yunbi#4]
Due to the recent service instability of yunbi.com, I found sometimes my python script hang without throwing exceptions. I believe this is something related to the Requests module. 
Not sure if you can add timeout on all public/private API requests to ensure when there is no response after X seconds, an exception is always raised ?

**Comment by imlonghao** [comment]
Hi there,

A new commit 04fb228 have been released which contained the timeout feature.
By default the timeout is 5 seconds, you can also change this value. For example:

```
from yunbi import Yunbi
y = Yunbi(timeout=1)
```

You can upgrade to v0.2.2 by using pip:

```
$ pip install -U yunbi
```

Thanks.
